# application

server:
  port: 8080
  servlet:
    context-path: /api/v1.0

spring:
  application:
    name: quiz-edu
  profiles:
    active: @spring.profiles.active@
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    web: info
    root: info
